# Generated by Django 3.1 on 2020-09-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20200902_2030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Collaborator',
        ),
        migrations.AlterModelTable(
            name='collaborator',
            table='collaborator',
        ),
    ]
