# Generated by Django 3.1 on 2020-09-04 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20200902_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'tip',
                'verbose_name_plural': 'tipos',
                'db_table': 'type',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='collaborator',
            name='type_collaborator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.type'),
        ),
    ]
