# Generated by Django 3.1 on 2020-09-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20200904_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'db_table': 'category',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['id'], 'verbose_name': 'tipo', 'verbose_name_plural': 'tipos'},
        ),
        migrations.AddField(
            model_name='collaborator',
            name='categ',
            field=models.ManyToManyField(to='erp.Category'),
        ),
    ]
